extends Node
## Audio: pooled SFX with variation, adaptive music (synchronized stems + crossfades),
## ambience beds and character voice blips. Assets are generated by tools/audio and live in
## res://assets/audio/{music,sfx,ambience}. Missing assets are reported once, never fatal.

const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"
const AMB_DIR := "res://assets/audio/ambience/"
const POOL := 14
const POOL_3D := 10
const CROSSFADE := 3.0

## Music cues and their stems. Every stem in a cue has identical length (rendered so).
const CUES := {
	"menu": ["pad", "melody", "glass"],
	"wick": ["pad", "melody", "counter", "pulse"],
	"hush": ["pad", "glass", "melody"],
	"reach": ["drone", "glass", "pulse"],
	"cut": ["bass", "ostinato", "perc", "alarm"],
	"station": ["pad", "brass", "knock", "melody"],
}

var _sfx: Dictionary = {}                ## name -> Array[AudioStream]
var _pool: Array[AudioStreamPlayer] = []
var _pool3d: Array[AudioStreamPlayer3D] = []
var _missing: Dictionary = {}
var _rng := RandomNumberGenerator.new()

# Music
var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _active_music: AudioStreamPlayer
var _cue := ""
var _cue_streams: Dictionary = {}        ## cue -> AudioStreamSynchronized
var _stem_targets: Dictionary = {}       ## stem name -> linear gain target
var _stem_current: Dictionary = {}
var _fade_t := 0.0
var _crisis := 0.0
var _crisis_target := 0.0

# Ambience
var _amb_a: AudioStreamPlayer
var _amb_b: AudioStreamPlayer
var _amb_name := ""
var _amb_fade := 1.0

# Voice
var _voice: AudioStreamPlayer
var _voice_cache: Dictionary = {}


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_rng.randomize()
	for i in POOL:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_pool.append(p)
	for i in POOL_3D:
		var p3 := AudioStreamPlayer3D.new()
		p3.bus = "SFX"
		p3.unit_size = 8.0
		p3.max_distance = 40.0
		p3.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE
		add_child(p3)
		_pool3d.append(p3)
	_music_a = _make_player("Music")
	_music_b = _make_player("Music")
	_active_music = _music_a
	_amb_a = _make_player("Ambience")
	_amb_b = _make_player("Ambience")
	_voice = _make_player("Voice")


func _make_player(bus: String) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.bus = bus
	add_child(p)
	return p


# --- SFX ------------------------------------------------------------------------------------

func _variants(name: String) -> Array:
	if _sfx.has(name):
		return _sfx[name]
	var list: Array = []
	for i in range(1, 9):
		var path := "%s%s_%d.ogg" % [SFX_DIR, name, i]
		if ResourceLoader.exists(path):
			list.append(load(path))
	if list.is_empty():
		var single := "%s%s.ogg" % [SFX_DIR, name]
		if ResourceLoader.exists(single):
			list.append(load(single))
	if list.is_empty() and not _missing.has(name):
		_missing[name] = true
		Log.warn("audio", "missing sfx '%s'" % name)
	_sfx[name] = list
	return list


## Plays a non-positional sound (UI, player feedback). Returns the player used.
func play(name: String, volume_db := 0.0, pitch_var := 0.05, bus := "SFX") -> AudioStreamPlayer:
	var v := _variants(name)
	if v.is_empty():
		return null
	var p := _free_player()
	p.stream = v[_rng.randi_range(0, v.size() - 1)]
	p.volume_db = volume_db
	p.pitch_scale = 1.0 + _rng.randf_range(-pitch_var, pitch_var)
	p.bus = bus
	p.play()
	return p


func ui(name: String, volume_db := -4.0) -> void:
	play(name, volume_db, 0.02, "UI")


## Plays a positional sound in the 3D world.
func play_at(name: String, pos: Vector3, volume_db := 0.0, pitch_var := 0.06) -> void:
	var v := _variants(name)
	if v.is_empty():
		return
	var best: AudioStreamPlayer3D = _pool3d[0]
	for p in _pool3d:
		if not p.playing:
			best = p
			break
	best.stream = v[_rng.randi_range(0, v.size() - 1)]
	best.global_position = pos
	best.volume_db = volume_db
	best.pitch_scale = 1.0 + _rng.randf_range(-pitch_var, pitch_var)
	best.play()


func _free_player() -> AudioStreamPlayer:
	for p in _pool:
		if not p.playing:
			return p
	return _pool[0]


func stream(name: String) -> AudioStream:
	var v := _variants(name)
	return v[0] if not v.is_empty() else null


# --- Music ----------------------------------------------------------------------------------

func _cue_stream(cue: String) -> AudioStreamSynchronized:
	if _cue_streams.has(cue):
		return _cue_streams[cue]
	var stems: Array = CUES.get(cue, [])
	var sync := AudioStreamSynchronized.new()
	var loaded := 0
	sync.stream_count = stems.size()
	for i in stems.size():
		var path := "%s%s_%s.ogg" % [MUSIC_DIR, cue, stems[i]]
		if ResourceLoader.exists(path):
			var s: AudioStream = load(path)
			if s is AudioStreamOggVorbis:
				(s as AudioStreamOggVorbis).loop = true
			sync.set_sync_stream(i, s)
			sync.set_sync_stream_volume(i, -60.0)
			loaded += 1
	if loaded == 0:
		if not _missing.has("cue:" + cue):
			_missing["cue:" + cue] = true
			Log.warn("audio", "missing music cue '%s'" % cue)
		_cue_streams[cue] = null
		return null
	_cue_streams[cue] = sync
	return sync


## Switches the music cue (crossfade) and sets the target stem gains (0..1 per stem).
func music(cue: String, stems: Dictionary = {}) -> void:
	if cue != _cue:
		var s := _cue_stream(cue)
		_cue = cue
		var nxt := _music_b if _active_music == _music_a else _music_a
		nxt.stream = s
		nxt.volume_db = -60.0
		if s != null:
			nxt.play()
		_active_music = nxt
		_fade_t = 0.0
		_stem_current.clear()
	_stem_targets = stems


func set_stems(stems: Dictionary) -> void:
	_stem_targets = stems


func crisis(amount: float) -> void:
	_crisis_target = clampf(amount, 0.0, 1.0)


func current_cue() -> String:
	return _cue


func _process(delta: float) -> void:
	# Crossfade between music players.
	_fade_t = minf(_fade_t + delta / CROSSFADE, 1.0)
	var other := _music_b if _active_music == _music_a else _music_a
	_active_music.volume_db = linear_to_db(maxf(_fade_t, 0.0001))
	other.volume_db = linear_to_db(maxf(1.0 - _fade_t, 0.0001))
	if _fade_t >= 1.0 and other.playing:
		other.stop()
	# Stem gains glide toward their targets.
	var sync := _active_music.stream as AudioStreamSynchronized
	if sync != null:
		var names: Array = CUES.get(_cue, [])
		for i in names.size():
			var target := float(_stem_targets.get(names[i], 1.0 if i == 0 else 0.0))
			var cur := float(_stem_current.get(names[i], 0.0))
			cur = move_toward(cur, target, delta * 0.35)
			_stem_current[names[i]] = cur
			sync.set_sync_stream_volume(i, linear_to_db(maxf(cur, 0.0001)))
	# Crisis colouring on the music bus: low-pass closes, a little drive.
	_crisis = move_toward(_crisis, _crisis_target, delta * 0.3)
	var bus := AudioServer.get_bus_index("Music")
	if bus >= 0 and AudioServer.get_bus_effect_count(bus) >= 2:
		var lp := AudioServer.get_bus_effect(bus, 0) as AudioEffectLowPassFilter
		lp.cutoff_hz = lerpf(20000.0, 900.0, _crisis)
		var dist := AudioServer.get_bus_effect(bus, 1) as AudioEffectDistortion
		dist.drive = _crisis * 0.35
		AudioServer.set_bus_effect_enabled(bus, 1, _crisis > 0.05)
	# Ambience crossfade.
	_amb_fade = minf(_amb_fade + delta / 4.0, 1.0)
	_amb_a.volume_db = linear_to_db(maxf(_amb_fade, 0.0001))
	_amb_b.volume_db = linear_to_db(maxf(1.0 - _amb_fade, 0.0001))
	if _amb_fade >= 1.0 and _amb_b.playing:
		_amb_b.stop()


# --- Ambience -------------------------------------------------------------------------------

func ambience(name: String) -> void:
	if name == _amb_name:
		return
	_amb_name = name
	var path := "%s%s.ogg" % [AMB_DIR, name]
	var s: AudioStream = load(path) if ResourceLoader.exists(path) else null
	if s is AudioStreamOggVorbis:
		(s as AudioStreamOggVorbis).loop = true
	if s == null and not _missing.has("amb:" + name):
		_missing["amb:" + name] = true
		Log.warn("audio", "missing ambience '%s'" % name)
	# Swap roles: the old bed fades out on B, the new bed fades in on A.
	var old_stream := _amb_a.stream
	var old_pos := _amb_a.get_playback_position() if _amb_a.playing else 0.0
	_amb_b.stream = old_stream
	if old_stream != null:
		_amb_b.play(old_pos)
	_amb_a.stream = s
	if s != null:
		_amb_a.play()
	_amb_fade = 0.0


# --- Voices -----------------------------------------------------------------------------------

## A short voice blip for a typed character; pitch varies per character for speech-like rhythm.
func voice_blip(timbre: String, pitch: float, char_code: int) -> void:
	var s: AudioStream = _voice_cache.get(timbre)
	if s == null:
		var path := "%svoice_%s.ogg" % [SFX_DIR, timbre]
		if not ResourceLoader.exists(path):
			return
		s = load(path)
		_voice_cache[timbre] = s
	if _voice.playing and _voice.get_playback_position() < 0.045:
		return
	_voice.stream = s
	_voice.pitch_scale = pitch * (0.92 + float(char_code % 7) * 0.025)
	_voice.volume_db = -8.0
	_voice.play()
